module.exports = {
  QUIC_SESSION_STREAM_FRAME_SENT : 'S',
  QUIC_SESSION_STREAM_FRAME_RECEIVED : 'R',
  QUIC_HTTP_STREAM_SEND_REQUEST_HEADERS : 'HS',
  QUIC_SESSION_RST_STREAM_FRAME_SENT : 'RST',
  QUIC_SESSION_PACKET_SENT: 'PS',
  QUIC_SESSION_UNAUTHENTICATED_PACKET_HEADER_RECEIVED: 'HR',
  QUIC_SESSION_ACK_FRAME_RECEIVED: 'AR',
  QUIC_SESSION_ACK_FRAME_SENT: 'AS'
};
